### ISSUE TITLE
DB_COLUMN到JavaFIELD的自定义映射规则错误

### ISSUE THREAD

**Issue by Splinglove** [GeeQuery/ef-orm#10]
如数据库字段为s_username，默认转成的Javafield为sUsername，这个时候生成的get，set方法，在执行插入操作时找不到sUsername字段错误。
处理:增加用户自定义处理接口，可以操作字段去除前缀，后缀等自定义操作，从而生成用户想要的beanfield

**Comment by xuse** [comment]
该问题是代码生成插件在处理第二个字母大写的方法属性时，getter和setter处理不对。根据java Bean规范。
````
private int pId
public int getpId(){
}
public void setpId(){
}
````
中的首字母无需改为大写，而代码生成时改为大写，造成Bean属性访问器无法正常访问该Bean。
解决办法为修改代码生成插件。
修复后的代码生成插件可以从 http://geequery.github.io/plugins/1.3.x/  的Update site进行更新。
