### ISSUE TITLE
Road Map of 1.12

### ISSUE THREAD

**Issue by xuse** [GeeQuery/ef-orm#53]
## 数据库结构对比和数据初始化增强
1. 增加对Index和constrant的对比和更新。(目前基本具备，表结构升级还需继续测试)。
2. 增加对数据库结构和数据初始化的特性规范，将此功能实用化。
3. 使用CSV格式作为初始化数据，原有的JSON方案不再支持。

**Comment by xuse** [comment]
1、增加对Index和constrant的对比和更新。
2、Unique约束不再用 unique index这种方式“曲线实现”
3、增加对数据库结构和数据初始化的特性规范，将此功能实用化。
3、适当删减一些不够稳定的特性。

由于目前实现过于复杂，此版本后，原则上V1除修改BUG外不再增加新特性。

**Comment by xuse** [comment]
一个新思路：为SQL Parser加上缓存。如果能保证SQL语句全部都用了绑定变量，那么一个应用的SQL总数其实是相当有限的，此时解析器的效率就不再是那么重要了。这可以解决目前JavaCC的解析器效率较低的问题。

**Comment by linziguan** [comment]
发现这个框加很不错。

**Comment by xuse** [comment]
#3 Finished.

**Comment by xuse** [comment]
1.12中还需增加的特性
1、使用spring-instrument来实现ef的动态增强
2、增加注解@FindBy，提高Spring-Data方式使用效率。
3、使用QueryDSL改进Spring-data的使用
4、支持使用注解+增加脚本，定义数据后处理行为
5、支持Spring-boot的自动配置
