### ISSUE TITLE
Question: Does not support DOUBLE type

### ISSUE THREAD

**Issue by DiamondIsMingzai** [GeeQuery/ef-orm#68]
May I ask a question？ Why this project does not support DOUBLE type?

**Comment by xuse** [comment]
First ,there's no data type 'DOUBLE' in Oracle.
----
And as in Postgresql ( From Manual of postgresql)
>8.1.3. Floating-Point Types

>The data types real and double precision are inexact, variable-precision numeric types. In practice, these types are usually implementations of IEEE Standard 754 for Binary Floating-Point Arithmetic (single and double precision, respectively), to the extent that the underlying processor, operating system, and compiler support it.

>Inexact means that some values cannot be converted exactly to the internal format and are stored as approximations, so that storing and retrieving a value might show slight discrepancies. Managing these errors and how they propagate through calculations is the subject of an entire branch of mathematics and computer science and will not be discussed here, except for the following points:

>If you require exact storage and calculations (such as for monetary amounts), use the numeric type instead.

>If you want to do complicated calculations with these types for anything important, especially if you rely on certain behavior in boundary cases (infinity, underflow), you should evaluate the implementation carefully.

>Comparing two floating-point values for equality might not always work as expected.

----
And as in MySQL ( From Manual of MySQL)
> B.5.4.8 Problems with Floating-Point Values

> Floating-point numbers sometimes cause confusion because they are approximate and not stored as exact values. A floating-point value as written in an SQL statement may not be the same as the value represented internally. Attempts to treat floating-point values as exact in comparisons may lead to problems. They are also subject to platform or implementation dependencies. The FLOAT and DOUBLE data types are subject to these issues. For DECIMAL columns, MySQL performs operations with a precision of 65 decimal digits, which should solve most common inaccuracy problems.

----
It's strongly recommended to use NUMERIC or NUMBER replace of DOUBLE and FLOAT
````
     @Column(columnDefinition="NUMERIC",precision=20,scale=12)  //or "NUMBER"
    private double volume;
    
````
----
Finally, If you really want to define a DOUBLE type, I ll pull https://github.com/xuse/ef-orm/commit/d34a815782f71e83834ade2baec2cf4e102ed0f2 to the next release.
