### ISSUE TITLE
EntityEnhancer.enhanceClass方法进行enhance存在错误

### ISSUE THREAD

**Issue by nihf** [GeeQuery/ef-orm#76]
EntityEnhancer.enhanceClass方法进行enhance存在错误

return enhance(file.getLocalFile(),string);

private boolean enhance(File f,String cls) throws IOException, Exception {
        EnhanceTaskASM enhancer=new EnhanceTaskASM(null,roots);
        File sub = new File(f.getParentFile(), cls.replace('.', '/').concat("$Field.class"));

这里的sub获取到的地址存在问题。

**Comment by xuse** [comment]
可否提个Case，或者直接Pull修复逻辑过来？

**Comment by xuse** [comment]
Merged.
