### ISSUE TITLE
可以考虑采用EntityWrapper来代替IQueryableEntity或DataObject

### ISSUE THREAD

**Issue by linziguan** [GeeQuery/ef-orm#77]
/*
	 * User 查询包装器
	 */
	private EntityWrapper<User> ew = new EntityWrapper<User>();
@Test
	public void test11() {
		/*
		 * 实体带where ifneed
		 */
		ew.setEntity(new User(1));
		ew.where("name={0}", "'123'").addFilterIfNeed(false, "id=12");
		String sqlSegment = ew.getSqlSegment();
		System.err.println("test11 = " + sqlSegment);
		Assert.assertEquals("AND (name='123')", sqlSegment);
	}

以上代码截取自https://git.oschina.net/baomidou/mybatis-plus

**Comment by xuse** [comment]
这个想法不错。用外加的wrapper对象来包装条件等。
关于POJO和继承DataObjec，后者主要有以下用途——
* 通过增强功能修改字节码，在每个类中set方法中记录被操作过的标记
* 通过增强功能修改字节码，在每个类中get方法中判断是否触发延迟加载功能。
(上述两个功能都直接调用了父类(DataObject)中的方法，因此植入的代码量很小。当然，改用POJO以后一样可以植入代码。)
* 通过内含的Query对象，记录用户查询条件
* 通过内含的updateValueMap，记录用户set过的值，从而形成update的语句。
----
从建议来看，用Wrapper可以换一个形态来记录Entity的状态。不过API变化会比较大，我比较倾向是在2.0的新版本里面规划。
但是怎么说呢，可以在下次重构时候考虑，在不改变现有API的情况下，用这种方式增强对POJO的支持。
（其实现在就是可以操作POJO的CRUD的，只不过延迟加载等高级特性都不支持POJO）

**Comment by linziguan** [comment]
谢谢，持续关注您的框架!
