### ISSUE TITLE
Debug模式下类动态加载的问题

### ISSUE THREAD

**Issue by zhanjiejun** [GeeQuery/ef-orm#78]
**操作步骤：**

1. 在Debug模式下启动工程，修改实体类并保存，关闭进程；

2. 重新在Debug模式下启动工程，触发调用实体类的setter方法，不会在updateValueMap中加入相应的field。

**影响：**

- 单个更新时，判断到没有更新的字段，不会去更新数据库中字段

- 批量更新时，会导致没有调用过setter的方法的字段被更新为Null

**Comment by xuse** [comment]
以前使用预加载类并在Eclipse中增加插件支持，后来Eclipse逐渐分化后取消了热加载功能。
计划在1.12.x中采用java instrument解决。

**Comment by xuse** [comment]
明确路线图，1,12.x中解决。

**Comment by xuse** [comment]
通过1.12.x支持spring-instrument解决。
