### ISSUE TITLE
使用getSession().load(query, true)，设置 query.setCascade(true);对应的关联对象任然无法获取到

### ISSUE THREAD

**Issue by nihf** [GeeQuery/ef-orm#86]
DbUtils.toReferenceJoinQuery 方法中的
select.merge((AbstractEntityMappingProvider) queryObj.getSelectItems());
代码，
将导致getSession().load(query, true);中，
如果设置
query.setCascade(true);
那么对应的关联对象任然无法获取到

**Comment by nihf** [comment]
new PKQuery<T>(meta, key);
创建的Query会导致设置setCascade无效。

如果是QueryBuilder.create(entityClass);
创建的Query，即使不设置setCascade，也是会级联获取。

**Comment by xuse** [comment]
····
import jef.orm.multitable.model.Person;
import jef.orm.multitable.model.School;
import jef.orm.multitable.model.Score;

    @Test
    @IgnoreOn(allButExcept={"hsqldb"})
    public void testMerge() throws SQLException {
        Query<Person> query=new PKQuery(MetaHolder.getMeta(Person.class),1);
        query.setCascade(false);
        Person p=db.load(query,false);
        System.out.println(p);
    }
····
[上述案例中的类Person等Entity源码见这里](../tree/master/orm-test/src/test/java/jef/orm/multitable/model)

**Comment by xuse** [comment]
Seems fixed. but I shall push more test cases later.
